services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8862:8862"
      - "80:80"
    volumes:
      - ./conf_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf_nginx/frontend_img:/usr/share/nginx/frontend_img:ro
    depends_on:
      - backend
      - frontend

  pgdb:
    image: postgres
    restart: "always"
    shm_size: "1gb"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      PGSSLMODE: "disable"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data_pg2:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:${DB_PORT}"

  backend:
    build:
      context: ./booking-system
      dockerfile: dockerfile_backend
    restart: "always"
    stdin_open: true  # 保持標準輸入打開，允許容器內部接受交互。
    tty: true  # 分配一個虛擬終端給容器，使得它可以進行交互式操作。
    env_file:
      - .env
    environment:
      - RECEIVER_HOST=0.0.0.0
      - POST=8850
    depends_on:
      - pgdb

  frontend:
    build:
      context: ./booking-system
      dockerfile: dockerfile_frontend
    restart: "always"
    stdin_open: true
    tty: true
