services:
  pgdb:
    image: postgres
    restart: "always"
    shm_size: "1gb"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      PGSSLMODE: "disable"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data_pg2:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:${DB_PORT}"

  backend:
    build:
      context: ./booking-system
      dockerfile: dockerfile_backend
    restart: "always"
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - POST=8800
    depends_on:
      - pgdb
