services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8862:8862"
    volumes:
      - ./conf_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  pgdb:
    image: postgres
    restart: "always"
    shm_size: "1gb"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      PGSSLMODE: "disable"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data_pg2:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:${DB_PORT}"

  backend:
    build:
      context: ./booking-system
      dockerfile: dockerfile_backend
    restart: "always"
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - RECEIVER_HOST=0.0.0.0
      - POST=8850
    depends_on:
      - pgdb
